WaterDeliver/Controllers/Admin/CompanyPayTypeController.cs
using Common;
using Common.BusinessHelper;
using Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WaterDeliver.Controllers.Admin
{
    public class CompanyPayTypeController : Admin_BaseController
    {
        // GET: CompanyPayType
        public ActionResult Index()
        {
            var payTypes = CompanyPayTypeHelper.PayTypeList();
            var salaryPayType = payTypes.FirstOrDefault(i => i.Id == SalaryPayType);
            if (salaryPayType == null)
            {
                //初次加载，初始化薪资支出与进水支出类别，且不允许删除
                List<CompanyPayType> payTypeMods = new List<CompanyPayType>
                {
                    new CompanyPayType
                    {
                        Id = SalaryPayType,
                        PayType = "员工薪资支出"
                    },
                    new CompanyPayType
                    {
                        Id = BucketPayType,
                        PayType = "进水支出"
                    }
                };
                MongoBase.Insert(payTypeMods);
            }
            ViewBag.flag = "payTypes";
            return View(payTypes);
        }

        public ActionResult Create(CompanyPayType companyPayType)
        {
            companyPayType.Id = ObjectId.NewObjectId().ToString();

            MongoBase.Insert<CompanyPayType>(companyPayType);
            return RedirectToAction("index");
        }

        public ActionResult Delete(string id)
        {
            CompanyPayTypeHelper.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

WaterDeliver/Views/CompanyPayType/Index.cshtml
@model IEnumerable<Model.CompanyPayType>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_admin.cshtml";
}

<script src="~/scripts/layer/layer.js"></script>
<script>
    @*$(function () {
        var err = '@ViewBag.checkSalary';
        if (err != "") {
            layer.alert(err, {
                skin: 'layui-layer-molv' //样式类名  自定义样式
                    , closeBtn: 1    // 是否显示关闭按钮
                    , anim: 1 //动画类型
                    , icon: 6
            });
        }
    });*@
</script>

<div class="panel panel-info">
    <div class="panel-heading">
        <h4 class="panel-title">类别信息</h4>
    </div>
    <div class="panel-body">
        <div><label style="color: red;">【薪资支出】与【进水支出】系统会自动维护，请不要添加或删除</label></div>
        <table class="table table-hover table-condensed">
            <thead style="background-color: lightblue"><tr><th>ID</th><th>类别名称</th><th>描述</th><th>操作</th></tr></thead>
            @if (Model != null)
            {
                int i = 0;
                foreach (var item in Model)
                {
                    <tr>
                        <td>@i</td>
                        <td>@item.PayType</td>
                        <td>@item.PayTypeDescribe</td>
                        <td>@Html.ActionLink("删除", "Delete", "CompanyPayType", new {id = item.Id}, new {@class = "btn btn-xs btn-danger", onclick = "return confirm('确认删除？')"})</td>
                    </tr>
                    i++;
                }
            }

        </table>
    </div>
</div>
<form class="form-horizontal" method="post" action="/CompanyPayType/Create">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h4 class="panel-title">添加产品</h4>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <label class="col-sm-1 control-label" for="txtPayType">类别名称</label>
                <input type="text" required class="form-control" style="width: 200px" id="txtPayType" name="PayType" />
            </div>
            <div class="form-group">
                <label class="col-sm-1 control-label" for="txtPayTypeDescribe">描述</label>
                <textarea class="form-control" name="PayTypeDescribe" id="txtPayTypeDescribe" rows="3" style="width:400px"></textarea>
            </div>
            <input type="submit" value="提交" class="btn btn-primary" />
        </div>
    </div>
</form>