WaterDeliver/Controllers/Admin/CustomerController.cs
using Common;
using Common.BusinessHelper;
using Model;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WaterDeliver.Controllers.Admin
{
    public class CustomerController : Admin_BaseController
    {
        // GET: Product
        public ActionResult Index(int pageIndex = 1)
        {
            var customers = CustomerHelper.CustomerList();
            var currentCustomers = customers.Skip((pageIndex - 1) * PageSize()).Take(PageSize()).ToList();

            ViewBag.totalPage = customers.Count() % PageSize() == 0
                    ? customers.Count() / PageSize()
                    : Math.Ceiling(Convert.ToDouble(customers.Count()) / PageSize());
            ViewBag.totalSize = customers.Count;
            ViewBag.currentPage = pageIndex;

            ViewBag.flag = "customer";
            return View(currentCustomers);
        }

        public ActionResult Create(Customer customer)
        {
            customer.Id = ObjectId.NewObjectId().ToString();

            MongoBase.Insert<Customer>(customer);
            return RedirectToAction("index");
        }

        public ActionResult Delete(string id)
        {
            CustomerHelper.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

WaterDeliver/Controllers/Admin/FactoryController.cs
using Common;
using Common.BusinessHelper;
using Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WaterDeliver.Controllers.Admin
{
    /// <summary>
    /// 水厂管理
    /// </summary>
    public class FactoryController : Controller
    {
        // GET: Factory
        public ActionResult Index()
        {
            var factories = FactoryHelper.FactoryList();
            ViewBag.flag = "factory";
            return View(factories);
        }

        public ActionResult Create(Factory factory)
        {
            factory.Id = ObjectId.NewObjectId().ToString();
            MongoBase.Insert<Factory>(factory);
            return RedirectToAction("index");
        }

        public ActionResult Delete(string id)
        {
            StaffHelper.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

WaterDeliver/Controllers/Admin/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Common;
using Common.BusinessHelper;
using Model;
using Newtonsoft.Json;

namespace WaterDeliver.Controllers.Admin
{
    public class ProductController : Admin_BaseController
    {
        // GET: Product
        public ActionResult Index()
        {
            if (TempData["isRepeat"] != null)
            {
                ViewBag.Err = "该产品已存在，请修改名称再试";
                TempData.Remove("isRepeat");
            }
            var factories = FactoryHelper.FactoryList();
            var products = ProductHelper.ProductList();

            var newProducts = products.OrderByDescending(i => i.UpdateTime).Join(factories, x => x.FactoryId, y => y.Id, (x, y) => new ProductFac
            {
                Id = x.Id,
                ProductName = x.ProductName,
                CostPrice = x.CostPrice,
                StockRemain = x.StockRemain,
                BucketStockRemain = x.BucketStockRemain,
                BucketCostPrice = x.BucketCostPrice,
                SalePrice = x.SalePrice,
                UpdateTime = x.UpdateTime,
                FactoryName = y.FactoryName
            });

            ViewBag.Factories = factories;
            ViewBag.flag = "product";
            return View(newProducts);
        }

        public ActionResult Create(Products product)
        {
            //重名判断
            var pro = ProductHelper.GetByName(product.ProductName);
            if (pro != null)
            {
                TempData["isRepeat"] = true;
            }
            else
            {
                product.Id = ObjectId.NewObjectId().ToString();
                product.UpdateTime = DateTime.Now;
                MongoBase.Insert(product);
            }
            
            return RedirectToAction("index");
        }

        public ActionResult Delete(string id)
        {
            ProductHelper.Delete(id);
            DailyRecordHelper.DeleteMany(id);//日常记录中与该产品相关的记录都会删除
            return RedirectToAction("Index");
        }

        /// <summary>
        /// 产品库存维护
        /// </summary>
        /// <returns></returns>
        public ActionResult StockMaintain()
        {
            ViewBag.flag = "stockMaintain";
            var products = ProductHelper.ProductList();
            if (TempData["TheProduct"] != null)
            {
                ViewBag.TheProduct = TempData["TheProduct"];
            }
            return View(products);
        }

        public ActionResult AddStockAmount(string productId, int numToAdd, int numToReadd)
        {
            var product = ProductHelper.GetById(productId);
            product.StockRemain = product.StockRemain + numToAdd;
            product.BucketStockRemain = product.BucketStockRemain - numToReadd;
            product.UpdateTime = DateTime.Now;
            ProductHelper.Update(product);
            TempData["TheProduct"] = JsonConvert.SerializeObject(product);
            return RedirectToAction("StockMaintain");
        }
    }
}

WaterDeliver/Controllers/Admin/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Common;
using Common.BusinessHelper;
using Model;

namespace WaterDeliver.Controllers.Admin
{
    public class StaffController : Admin_BaseController
    {
        // GET: Staff
        public ActionResult Index()
        {
            var staffs = StaffHelper.StaffList();
            ViewBag.flag = "staff";
            return View(staffs);
        }
        
        public ActionResult Create(Staff staff)
        {
            staff.Id = ObjectId.NewObjectId().ToString();
            MongoBase.Insert<Staff>(staff);
            return RedirectToAction("index");
        }

        public ActionResult Delete(string id)
        {
            StaffHelper.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

WaterDeliver/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/scripts/Font-Awesome-3.2.1/css/font-awesome.min.css" rel="stylesheet" />
    <script src="~/scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/scripts/layer/layer.js"></script>
</head>
<body>
    <div class="navbar navbar-nav navbar-fixed-top" style="background-color:powderblue">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLinkWithImage(Url.Content("~/Images/logo01.png"), "Index", "Admin_Home")
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        <div class="col-md-2" style="margin-top:30px">
            <div class="well" style="padding: 8px 0;">
                <ul class="nav nav-pills nav-stacked">
                    <li id="DailyWrite"><a href="/Home/DailyWrite"><i class="icon-pencil"></i>&nbsp;每日一记</a></li>
                    <li id="DailyRecord"><a href="/Home/DailyRecord"><i class="icon-align-justify"></i>&nbsp;日常记录</a></li>
                    <li id="MonthEnd"><a href="/Home/MonthEnd"><i class="icon-money"></i>&nbsp;月底结算</a></li>
                    <li id="CompanyPay"><a href="/Home_Company/CompanyPay"><i class="icon-edit"></i>&nbsp;公司支出</a></li>
                    <li id="CompanyRecord"><a href="/Home_Company/CompanyRecord"><i class="icon-strikethrough"></i>&nbsp;公司记录</a></li>
                    <li id="CompanyEnd"><a href="/Home_Company/CompanyEnd"><i class="icon-book"></i>&nbsp;公司结算</a></li>
                    <li id="EndSummary"><a href="/Summary/Index"><i class="icon-book"></i>&nbsp;月底盈利与工资发放</a></li>
                    <li id="SalaryRecord"><a href="/Summary/SalaryList"><i class="icon-book"></i>&nbsp;员工工资查看</a></li>
                    <li id="FactoryTransRecord"><a href="/Home_Factory/TransRecord"><i class="icon-book"></i>&nbsp;水厂交易查看</a></li>
                    <li id="ProductCost"><a href="/Home_ProCost/Index"><i class="icon-book"></i>&nbsp;送水成本汇总</a></li>
                    @*<li id="CustomerAccessory"><a href="/Home_Accessory/Index"><i class="icon-book"></i>&nbsp;附属产品库存</a></li>*@
                    <li id="CompanyRecordsUptonow"><a href="/Home/CompanyRecordsUptonow"><i class="icon-book"></i>&nbsp;公司销售汇总</a></li>
                    <li id="DailyWrite"><a href="/Home/Index"><i class="icon-pencil"></i>&nbsp;送水提醒</a></li>
                </ul>
            </div>
        </div>
        <div class="col-md-10" style="padding-top:30px;padding-bottom:30px">
            @RenderBody()
        </div>
    </div>
    <div class="navbar navbar-inverse navbar-fixed-bottom" style="background-color:powderblue">
        <div class="container">
            <ul>
                @*<li>咨询热线：010-84505722</li>
                <li>地址：北京市朝阳区青年路西里2号院9号楼1层 </li>
                <li>Copyright &copy;@DateTime.Now.Year,All rights reserved版权所有 © 水递夫 技术支持北京网站建设公司企迪网 </li>*@
            </ul>
        </div>
    </div>
    <script type="text/javascript">
        $(function () {
            var flag = '@ViewBag.flag';
            if (flag != '') {
                $("#" + flag).addClass("active");
            }
        });
    </script>
</body>
</html>

WaterDeliver/Views/Shared/_Layout_admin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/scripts/Font-Awesome-3.2.1/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/scripts/pager/pageStyle.css" rel="stylesheet" />
    <script src="~/scripts/jquery-1.10.2.min.js"></script>
    <script src="~/scripts/layer/layer.js"></script>
    <script src="~/scripts/bootstrap.min.js"></script>
    <script src="~/scripts/pager/paging.js"></script>
    <script>
        $(function () {
            var flag = '@ViewBag.flag';
            if (flag != "") {
                $("#" + flag).addClass("active");
            } else {
                $("#customer").addClass("active");
                window.location.href = "Customer/Index";
            }
        });
    </script>
</head>
<body>
    <div class="navbar navbar-nav navbar-fixed-top" style="background-color: lightblue;">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLinkWithImage(Url.Content("~/Images/logo01.png"), "DailyWrite", "Home")
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        <div class="col-md-2" style="margin-top:80px">
            <div class="well" style="padding: 8px 0;">
                <ul class="nav nav-pills nav-stacked">
                    <li id="customer">@Html.ActionLink("客户管理", "Index", "Customer")</li>
                    <li id="product">@Html.ActionLink("产品管理", "Index", "Product")</li>
                    <li id="staff">@Html.ActionLink("员工管理", "Index", "Staff")</li>
                    @*<li id="stacus">@Html.ActionLink("员工_客户关系管理", "Index", "StaffCustomer")</li>*@
                    <li id="stockMaintain">@Html.ActionLink("库存管理", "StockMaintain", "Product")</li>
                    <li id="factory">@Html.ActionLink("供货商管理", "Index", "Factory")</li>
                    <li id="payTypes">@Html.ActionLink("公司消费类别管理", "Index", "CompanyPayType")</li>
                </ul>
            </div>
        </div>
        <div class="col-md-10" style="padding-top:30px;padding-bottom:35px">
            @RenderBody()
        </div>
    </div>
    <div class="navbar navbar-inverse navbar-fixed-bottom" style="background-color:lightblue">
        <div class="container">
            <ul>
                <li>咨询热线：010-84505722</li>
                <li>地址：北京市朝阳区青年路西里2号院9号楼1层 </li>
                <li>Copyright &copy;@DateTime.Now.Year,All rights reserved版权所有 © 水递夫 技术支持北京网站建设公司企迪网 </li>
            </ul>
        </div>
    </div>

</body>
</html>