WaterDeliver/Controllers/Admin/StaffCustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Common;
using Common.BusinessHelper;
using Model;

namespace WaterDeliver.Controllers.Admin
{
    public class StaffCustomerController : Admin_BaseController
    {
        // GET: StaffProject
        public ActionResult Index(int pageIndex = 1)
        {
            var staffs = StaffHelper.StaffList();
            var customers = CustomerHelper.CustomerList();
            var staffCustomer = StaffCustomerHelper.StaffCustomerList();
            var currentStaffCustomers = staffCustomer.Skip((pageIndex - 1) * PageSize()).Take(PageSize()).ToList();

            StaffCustomerViewModel viewModel = new StaffCustomerViewModel()
            {
                Staffs = staffs,
                Customers = customers,
                StaffCustomers = currentStaffCustomers
            };

            ViewBag.totalPage = staffCustomer.Count() % PageSize() == 0
                    ? staffCustomer.Count() / PageSize()
                    : Math.Ceiling(Convert.ToDouble(staffCustomer.Count()) / PageSize());
            ViewBag.totalSize = staffCustomer.Count;
            ViewBag.currentPage = pageIndex;

            ViewBag.flag = "stacus";
            return View(viewModel);
        }

        public ActionResult Delete(string id)
        {
            StaffCustomerHelper.Delete(id);
            return RedirectToAction("Index");
        }

        public ActionResult Create(StaffCustomer staffCustomer)
        {
            staffCustomer.Id = ObjectId.NewObjectId().ToString();
            MongoBase.Insert(staffCustomer);
            return RedirectToAction("Index");
        }
    }
}

WaterDeliver/Views/StaffCustomer/Index.cshtml

@model Model.StaffCustomerViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_admin.cshtml";
}

@helper StaffInfo(string staffId)
{
    string staffName = Model.Staffs.First(item => item.Id == staffId).StaffName;
    <td>@staffName</td>
}

@helper CustomerInfo(string customerId)
{
    var customer = Model.Customers.First(item => item.Id == customerId);
    <td>@customer.CustomerName</td>
    <td>@customer.Address</td>
    <td>@customer.Phone</td>
}

<script type="text/javascript">
    $(function() {
        //获取分页数据
        function changePageIndex(num) {
            window.location.href = "/StaffCustomer/Index?pageIndex=" + num;
        }

        //展示分页div
        $("#page").paging({
            pageNo: @ViewBag.currentPage,
            totalPage: @ViewBag.totalPage,
            totalSize: @ViewBag.totalSize,
            callback: function (num) {
                changePageIndex(num);
            }
        });
    });
</script>

<div class="panel panel-info">
    <div class="panel-heading">
        <h4 class="panel-title">员工客户关系管理</h4>
    </div>
    <div class="panel-body">
        <table class="table table-hover table-condensed">
            <thead style="background-color:lightblue"><tr><th>ID</th><th>员工姓名</th><th>客户名称</th><th>地址</th><th>联系方式</th><th>操作</th></tr></thead>
            @if (Model != null)
            {
                int i = 0;
                foreach (var item in Model.StaffCustomers)
                {
                    <tr>
                        <td>@i</td>
                        @StaffInfo(item.StaffId)
                        @CustomerInfo(item.CustomerId)
                        <td>@Html.ActionLink("删除", "Delete", "StaffCustomer", new { id = item.Id }, new { @class = "btn btn-xs btn-danger", onclick = "return confirm('确认删除？')" })</td>
                    </tr>
                    i++;
                }
            }

        </table>
        <div class="page_div" id="page"></div>
    </div>
</div>
<form class="form-horizontal" method="post" action="/StaffCustomer/Create">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h4 class="panel-title">为员工添加客户</h4>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <label class="col-sm-1 control-label" for="selStaff">员工</label>
                <select name="StaffId" id="selStaff" class="selectpicker show-tick form-control col-sm-2" style="width: 150px" required data-live-search="true">
                    @if (Model?.Staffs != null && Model.Staffs.Count > 0)
                    {
                        foreach (var item in Model.Staffs)
                        {
                            <option value="@item.Id">@item.StaffName</option>
                        }
                    }
                </select>
            </div>
            <div class="form-group">
                <label class="col-sm-1 control-label" for="selCustomer">客户</label>
                <select name="CustomerId" id="selCustomer" class="selectpicker show-tick form-control col-sm-2" style="width: 400px" required data-live-search="true">
                    @if (Model?.Customers != null && Model.Customers.Count > 0)
                    {
                        foreach (var item in Model.Customers)
                        {
                            <option value="@item.Id">@item.CustomerName</option>
                        }
                    }
                </select>
            </div>
            <input type="submit" value="提交" class="btn btn-primary" />
        </div>
    </div>
</form>
